### ISSUE TITLE
Testing ORM

### ISSUE THREAD

**Issue by francescobianco** [AdrienRedon/mvc#3]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by AdrienRedon** [comment]
Hi, I don't have much time to try it right now but I'll consider it. Thanks :slightly_smiling_face:
